# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z4x7T8fkLPd_pMeB2vcKu9JYtVJJGNXl
"""

!pip install requests beautifulsoup4 pandas -q

import requests

from bs4 import BeautifulSoup

import pandas as pd

import time

categories = {
    "Laptops": "https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops",
    "Tablets": "https://webscraper.io/test-sites/e-commerce/allinone/computers/tablets",
    "Phones (Touch)": "https://webscraper.io/test-sites/e-commerce/allinone/phones/touch"
}

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36"
}

def fetch_page(url, page):
    full_url = f"{url}?page={page}"
    resp = requests.get(full_url, headers=HEADERS, timeout=15)
    soup = BeautifulSoup(resp.text, "html.parser")
    return soup

def parse_products(soup, category_name, base_url):
    products = []
    items = soup.find_all("div", class_="thumbnail")
    for item in items:
        title_tag = item.find("a", class_="title")
        price_tag = item.find("h4", class_="price")
        desc_tag = item.find("p", class_="description")
        reviews_tag = item.find("p", class_="pull-right")
        products.append({
            "category": category_name,
            "name": title_tag["title"] if title_tag else None,
            "price": price_tag.text.strip() if price_tag else None,
            "description": desc_tag.text.strip() if desc_tag else None,
            "reviews": reviews_tag.text.strip() if reviews_tag else None,
            "url": base_url
        })
    return products

def scrape_category(category_name, base_url, max_pages=2):
    all_items = []
    for page in range(1, max_pages + 1):
        soup = fetch_page(base_url, page)
        items = parse_products(soup, category_name, base_url)
        if not items:
            break
        all_items.extend(items)
    return all_items

all_products = []

for category_name, base_url in categories.items():
    print(f"Scraping category: {category_name}")
    items = scrape_category(category_name, base_url, max_pages=2)
    all_products.extend(items)
    print(f"  -> {len(items)} products collected")
    time.sleep(1)

print(f"Total products scraped across all categories: {len(all_products)}")

df = pd.DataFrame(all_products)
df.drop_duplicates(subset=["name", "category"], inplace=True)
df.reset_index(drop=True, inplace=True)
print("Final dataset shape:", df.shape)

df.to_csv("scraped_electronics_dataset.csv", index=False)
print("Saved as scraped_electronics_dataset.csv")

pd.set_option("display.max_rows", None)
pd.set_option("display.max_colwidth", None)

df

